encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    # Displays the contents of the markdown files for the wiki page
    path("wiki/<str:page>", views.page_render, name="content"),
    # Search page
    path("search", views.search_page, name="search"),
    # New page
    path("create", views.new_page, name="create"),
    # Already created page
    path("already_created/<str:title>", views.already_created, name="already_created"),
    # Edit page
    path("wiki/<str:page>/edit", views.editing_page, name="edit"),
    # Random page
    path("random", views.random_page, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render
from django.urls import reverse
import re
import markdown

from . import util

# Form class for editing an entry
class EditEntryForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 15,
        'cols': 80
        }), label="Edit the contents of the page below", initial="[Page Contents]")

# Form class for a new entry
class NewEntryForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'placeholder': "Title"
        }),
        label="Title:")
    # Uses the django form to get the text area
    text = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': "Your contents here",
        'rows': 15,
        'cols': 80
        }),
       label="Enter the contents of the page:")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Renders an arbitrary page using mardown.markdown to convert the markdwon to HTML
def page_render(request, page):
    # Try to get page, if markdown.markdown receives a None type (page not found) then redirect to 404 page
    try:
        page_contents = markdown.markdown(util.get_entry(page))
        return render(request, "encyclopedia/page_contents.html", {
            "title": page,
            "contents": page_contents
            })
    except AttributeError:
        return render(request, "encyclopedia/page_not_found.html")

# Search page
def search_page(request):
    # Get the user inputted search
    search_get = request.GET.get("q")
    # Ensure that lowercase inputs find the page (e.g., "css" will get to the CSS page)
    list_of_entries = util.list_entries()
    lower_list = [x.lower() for x in list_of_entries]
    search_low = search_get.lower()

    if search_low in lower_list:
        # This makes sure that the correct formatted page title is usedin as the page kwarg
        # In practice I'd think that this would be stored in an SQL DB otherwise that list is gonna suffer 
        i = lower_list.index(search_low)
        page = list_of_entries[i]
        # Need to add kwargs to specifiy the page
        return HttpResponseRedirect(reverse("wiki:content", kwargs={"page": page}))
    else:
        indices = []
        for i, element in enumerate(list_of_entries):
            if re.search(search_get, element, re.IGNORECASE):
                indices.append(i)
        search_results = [list_of_entries[x] for x in indices]
        return render(request, "encyclopedia/search_page.html", {
            "search_results": search_results
            })

def new_page(request):

    # Get form submitted by user
    if request.method == "POST":
        form = NewEntryForm(request.POST)

        # Validating server side
        if form.is_valid():
            # Get title and text
            title = (form.cleaned_data["title"]).capitalize()
            text = form.cleaned_data["text"]

            # Add a new entry
            if not title in util.list_entries():
                util.save_entry(title, text)
                return HttpResponseRedirect(reverse("wiki:index"))
            else:
                return HttpResponseRedirect(reverse("wiki:already_created", kwargs={"title": title}))

    return render(request, "encyclopedia/new_page.html", {
        "form": NewEntryForm()
        })

def already_created(request, title):
    return render(request, "encyclopedia/already_created.html", {
        "title": title
        })

# Editing a page
def editing_page(request, page):

    # Get updated entry submitted by user
    if request.method == "POST":
        update = EditEntryForm(request.POST)

        # Validating server side
        if update.is_valid():
            # Get updated text
            text = update.cleaned_data["text"]

            # Update the entry
            util.save_entry(page, text)
            return HttpResponseRedirect(reverse("wiki:content", kwargs={"page": page}))


    raw_contents = util.get_entry(page)

    return render(request, "encyclopedia/edit_page.html", {
        "title": page,
        "form": EditEntryForm(initial={'text': raw_contents})
        })

# Random page
def random_page(request):
    choices = util.list_entries()
    choice = random.choice(choices)
    return HttpResponseRedirect(reverse("wiki:content", kwargs={"page": choice}))


   

encyclopedia/templates/encyclopedia/already_created.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Error
{% endblock %}

{% block body %}
    <div style="text-align: center;">
        <h1> Error: Page already created!</h1>
        <img style="max-width:256px; max-height:256px; width: auto; height: auto;" src="https://media.tenor.com/0WyPJvp2ZwMAAAAd/cat-cats.gif" alt="Cat shocked gif">
        <br>
        <div style="margin: 50px;">
            <a href="{% url 'wiki:content' title %}">
                <button type="button" class="btn btn-info">View Page</button>
            </a>
            <a href="{% url 'wiki:index' %}">
                <button type="button" class="btn btn-dark">Home</button>
            </a>
        </div>
    </div> 

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Editing {{ title }}
{% endblock %}

{% block body %}
    <h1>Editing {{ title }}</h1>
    <div>
        {{ contents | safe  }}
    </div>
    <form style="display: flex; flex-direction: column; width: 80%;" method="POST">
        {% csrf_token %}
        <!-- Adds a break so there is one field under the other -->
        {{ form.text.label_tag }}
        <br>
        {{ form.text }}
        <br>
        <div style="display: flex; justify-content: space-between; margin-top: 20px;">
            <input type="submit" class="btn btn-info" value="Save">

            <a href="{% url 'wiki:content' title %}">
                <button type="button" class="btn btn-dark">Cancel</button>
            </a>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul class="list-group">
        {% for entry in entries %}
            <!-- Needed to add the "entry" at the end to specifiy what content should take -->
            <li class="list-group-item"><a href="{% url 'wiki:content' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2 class="display-4"><a id="main_heading" href="{% url 'wiki:index' %}">Wiki</a></h2>
                <form action="{% url 'wiki:search' %}">
                    <input class="form-control" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div class="sidebar_div">
                    <a class="sidebar_links" href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div class="sidebar_div">
                    <a class="sidebar_links" href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div class="sidebar_div">
                    <a class="sidebar_links" href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Create
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form method="POST">
        {% csrf_token %}
        <!-- Adds a break so there is one field under the other -->
        {{ form.title.label_tag }} {{ form.title }}
        <br>
        {{ form.text.label_tag }}
        <br>
        {{ form.text }}
        <br>
        <input type="submit" class="btn btn-info" value="Create"> 
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/page_contents.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}
    <h1 style="font-size: 64px; padding-top: 15px;" class="dsiplay-1">{{  title  }}</h1>
    <div>
        {{ contents | safe  }}
    </div>
    <div>
        <div>
            <a href="{% url 'wiki:edit' title %}">
                <button type="button" class="btn btn-dark">Edit</button>
            </a>
        </div>
        
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/page_not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - 404
{% endblock %}

{% block body %}
    <div style="text-align: center;">
        <h1> Error 404: Page not found!</h1>
        <img style="max-width:256px; max-height:256px; width: auto; height: auto;" src="https://media.tenor.com/GzsqGzYMpZEAAAAC/cat-meme.gif" alt="Cat loading gif">
        <div style="margin: 50px;">
            <a href="{% url 'wiki:create' %}">
                <button type="button" class="btn btn-info">Create Page</button>
            </a>
            <a href="{% url 'wiki:index' %}">
                <button type="button" class="btn btn-dark">Home</button>
            </a>
        </div>
    </div> 

{% endblock %}

encyclopedia/templates/encyclopedia/search_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Search
{% endblock %}

{% block body %}
    <h1>Search Results:</h1>

    {% if search_results %}
        <ul>
            {% for search_result in search_results %}
                <li><a href="{% url 'wiki:content' search_result %}">{{ search_result }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No results found!</h3>
    {% endif %}
{% endblock %}